UI/Models/Rdv.cs
namespace UI.Models
{
    public class Rdv
    {
        public int Id { get; set; }
        public string NomPatient { get; set; }
        public string NomPraticien { get; set; }
        public DateTime Date { get; set; }
    }
}

UI/Controllers/RdvController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
//using ApiRdv.Models;
using UI.Models;

namespace UI.Controllers
{
    public class RdvController : Controller
    {
        private readonly HttpClient _httpClient;


        public RdvController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://localhost:5001"); // Assurez-vous de mettre le bon port pour votre API Rdv
        }


        public async Task<IActionResult> Index(string nomPraticien, int praticienId, DateTime jourDisponible, int? annee, int? mois)
        {
            ViewData["NomPraticien"] = nomPraticien;
            ViewData["PraticienId"] = praticienId;
            ViewData["Date"] = jourDisponible;
            //  ViewData["AnneeSelectionnee"] = annee;

            // Récupérer l'année et le mois actuels par défaut
            int anneeActuelle = DateTime.Now.Year;
            int moisActuel = DateTime.Now.Month;

            // Utiliser les valeurs fournies ou les valeurs actuelles par défaut
            int anneeSelectionnee = annee ?? anneeActuelle;
            int moisSelectionne = mois ?? moisActuel;

            // Remplir les listes d'années et de mois pour les menus déroulants
            List<int> anneesDisponibles = Enumerable.Range(anneeActuelle, 10).ToList(); // 10 années à partir de l'année actuelle
            List<int> moisDisponibles = Enumerable.Range(1, 12).ToList(); // Les 12 mois

            // Calculer le nombre de jours dans le mois sélectionné
            //int nombreDeJoursDansMois = DateTime.DaysInMonth(anneeSelectionnee, moisSelectionne);
            int nombreDeJoursDansMois = moisSelectionne == 2 && EstBissextile(anneeSelectionnee) ? 29 : DateTime.DaysInMonth(anneeSelectionnee, moisSelectionne);


            // Créer une liste de dates pour le mois sélectionné
            List<DateTime> datesDuMois = new List<DateTime>();
            // Créer une liste de dates  disponibles pour le mois sélectionné
            List<DateTime> joursDisponibles = new List<DateTime>();

            for (int jour = 1; jour <= nombreDeJoursDansMois; jour++)
            {
                DateTime date = new DateTime(anneeSelectionnee, moisSelectionne, jour);
                datesDuMois.Add(date);
                joursDisponibles.Add(date);
            }

            //  ViewBag.Rdvs = listeRdvs;

            // Passer les données aux menus déroulants dans la vue
            ViewBag.Annees = new SelectList(anneesDisponibles, anneeSelectionnee);
            ViewBag.Mois = new SelectList(moisDisponibles, moisSelectionne);
            ViewBag.NombreDeJoursDansMois = nombreDeJoursDansMois;


            try
            {
                HttpResponseMessage response = await _httpClient.GetAsync("/api/Rdv");

                if (response.IsSuccessStatusCode)
                {
                    // Lecture et traitement des données
                    string responseData = await response.Content.ReadAsStringAsync();
                    // Désérialise la chaîne JSON en une liste d'objets
                    var listeRdvs = JsonConvert.DeserializeObject<List<Rdv>>(responseData);

                    // Filtrer les rendez-vous en fonction de nomPraticien
                    if (!string.IsNullOrEmpty(nomPraticien))
                    {
                        listeRdvs = listeRdvs.Where(rdv => rdv.NomPraticien == nomPraticien).ToList();
                    }
                    // Trier les rendez-vous par ordre chronologique
                    listeRdvs = listeRdvs.OrderBy(rdv => rdv.Date).ToList();

                    // Filtrer les jours disponibles en fonction des rendez-vous
                    joursDisponibles = joursDisponibles.Except(listeRdvs.Select(rdv => rdv.Date.Date)).ToList();

                    // Utilise les données comme nécessaire, peut-être passer à la vue
                    ViewBag.Rdvs = listeRdvs;
                    ViewBag.JoursDisponibles = joursDisponibles;

                    // Récupérez le message de confirmation depuis TempData
                    ViewBag.ConfirmationMessage = TempData["ConfirmationMessage"] as string;

                    return View();
                }
                else
                {
                    return StatusCode((int)response.StatusCode, $"Erreur HTTP: {response.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Erreur lors de la requête : {ex.Message}");
            }
        }
        private bool EstBissextile(int annee)
        {
            return (annee % 4 == 0 && annee % 100 != 0) || (annee % 400 == 0);
        }

        //public IActionResult Create(int praticienId, string nomPraticien)

        //{
        //    ViewData["PraticienId"] = praticienId;
        //    ViewData["NomPraticien"] = nomPraticien;
        //    // Affiche le formulaire de création de rendez-vous
        //    return View();
        //}

        public IActionResult Create(DateTime jourDisponible, int praticienId, string nomPraticien)

        {
            ViewData["PraticienId"] = praticienId;
            ViewData["NomPraticien"] = nomPraticien;
            ViewData["Date"] = jourDisponible;
            // Affiche le formulaire de création de rendez-vous
            return View();
        }


        [HttpPost]

        public async Task<IActionResult> Create(Rdv rdv)
        {

            try
            {
                await CreateRendezVousAsync(rdv);
                // Crée un objet de type UI.Models.Rdv avec les données nécessaires
                UI.Models.Rdv model = new UI.Models.Rdv
                {
                    NomPraticien = rdv.NomPraticien,
                    Id = rdv.Id,
                    Date = rdv.Date
                };
                // Ajoutez le message de confirmation à TempData
                TempData["ConfirmationMessage"] = "Le rendez-vous a été enregistré avec succès.";

                // Redirige vers l'action "Index" avec le modèle correct
                return RedirectToAction("Index", model);
                //return View("Home");
                //  ViewData["PraticienId"] = rdv.Id;
                //  ViewData["NomPraticien"] = rdv.NomPraticien;

                // return RedirectToAction("Index");
                //  return View("Index");
                //  return View("Index", new VotreModelePourLaVueIndex());
                //  return View("Index", new { nomPraticien = rdv.NomPraticien, praticienId = rdv.Id, jourDisponible = rdv.Date });
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);

            }
        }
        // Ajoutez d'autres actions selon les besoins de votre application

        private async Task CreateRendezVousAsync(Rdv rdv)
        {
            var response = await _httpClient.PostAsJsonAsync("api/Rdv", rdv); // Assurez-vous que l'URL est correcte

            if (!response.IsSuccessStatusCode)
            {
                var errorMessage = await response.Content.ReadAsStringAsync();
                throw new Exception(errorMessage);
            }
        }

    }



}

UI/Views/Rdv/Create.cshtml
@model UI.Models.Rdv

<h2>Créer un rendez-vous</h2>
<p>Praticien ID: @ViewData["PraticienId"]</p>
<p>Nom du Praticien: @ViewData["NomPraticien"]</p>
@* <p>jour disponible choisi :@ViewData["Date"]</p>
 *@
<p>jour disponible choisi :@(((DateTime)ViewData["Date"]).ToString("dd/MM/yyyy"))</p>




<form asp-action="Create" method="post" enctype="application/json">
    <div class="form-group">
        <label asp-for="NomPatient">Nom du Patient</label>
        <input asp-for="NomPatient" class="form-control" />
        <span asp-validation-for="NomPatient" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="NomPraticien">Nom du Praticien</label>
        <input asp-for="NomPraticien" class="form-control" />
        <span asp-validation-for="NomPraticien" class="text-danger"></span>
    </div>


    @{
        string dateISO8601 = ((DateTime)ViewData["Date"]).ToString("yyyy-MM-dd");
    }

    <div class="form-group">
        <label asp-for="Date">Date du Rendez-vous</label>
        <input asp-for="Date" type="date" class="form-control" value="@dateISO8601" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>


    <!-- Ajoutez d'autres champs si nécessaire -->

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Créer le rendez-vous</button>
    </div>
</form>

UI/Views/Rdv/Index.cshtml
@model UI.Models.Rdv

@{
    ViewData["Title"] = "Liste des Rendez-vous du Dr " + @ViewData["NomPraticien"] + @ViewData["PraticienId"];
}

<h1>@ViewData["Title"]</h1>

@* <p>Filtre par Nom du Praticien: @ViewData["NomPraticien"]</p> *@

<h3>
    <form method="get" asp-action="Index">
        <input type="hidden" name="PraticienId" value="@ViewData["PraticienId"]">
        <input type="hidden" name="NomPraticien" value="@ViewData["NomPraticien"]">
        <label for="Annee">Année :</label>
        @Html.DropDownList("annee", (SelectList)ViewBag.Annees, new { onchange = "this.form.submit()" })

        <label for="Mois">Mois :</label>
        @Html.DropDownList("mois", (SelectList)ViewBag.Mois, new { onchange = "this.form.submit()" })

    </form>
</h3>
@* @* <p>Nombre de jours dans le mois sélectionné : @ViewBag.NombreDeJoursDansMois</p>


<table class="table">
    <thead>
        <tr>
          @*   <th>ID</th>
            <th>Nom du Praticien</th>
            <th>Date</th>
            @* <th>Patient</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var rdv in ViewBag.rdvs)
        {
            <tr>
                @* <td>@rdv.Id</td>
                <td>@rdv.NomPraticien</td>
                <td>@rdv.Date.ToString("dddd, dd  MMMM yyyy")</td>
                @* <td>@rdv.NomPatient</td>
            </tr>
        }
    </tbody>
  </table>*@
<h3>Jours disponibles :</h3>
<table class="table">
    <thead>
        <tr>
            <th>Jour</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var jourDisponible in ViewBag.JoursDisponibles)
        {
            if (jourDisponible >= DateTime.Now.Date)
            {
                <tr>
                    <td>@jourDisponible.ToString("dddd")</td> <!-- Affiche le nom du jour -->
                    <td>@jourDisponible.ToString("dd/MM/yyyy")</td> <!-- Affiche la date -->
                    <td>
                        <a href="@Url.Action("Create", "Rdv", new { jourDisponible= @jourDisponible, praticienId = @ViewData["PraticienId"],nomPraticien=@ViewData["NomPraticien"] })" class="btn btn-primary">Prendre un rendez-vous</a>

                    </td>
                </tr>
            }

        }

    </tbody>
    @if (!string.IsNullOrEmpty(ViewBag.ConfirmationMessage))
    {
        <div class="alert alert-success">
            @ViewBag.ConfirmationMessage
        </div>
    }
</table>